import {Tabulator} from 'tabulator-tables';

var tabledata = [
    {
      Language: "Poumai Naga",
      Subfamily: "Angami-Pochuri",
      Source: "Veikho 2021",
      Coordinates: "26.12, 94.69",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "+",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "",
      Ev1: "+",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "+",
      Mir2: "+",
      Term_source: "evidential [277], particle [333,336] (marking maybe mirative)",
      AP_interrogative: "?",
      AP_declarative: "+ [138] demonstrative engagement",
      Diachronic: "",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "+",
      Nominal_Engagement: "+",
      Thesis: ""
    },
    {
      Language: "Tenyidie",
      Subfamily: "Angami-Pochuri",
      Source: "Kuolie 2006",
      Coordinates: "25.68, 93.87",
      Any_Marking: "-?",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "",
      AP_interrogative: "",
      AP_declarative: "",
      Diachronic: "",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Jejara",
      Subfamily: "Ao",
      Source: "Barkman 2014",
      Coordinates: "26.21, 95.16",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "",
      Ev1: "+",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "+",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "+",
      Term_source: "Reportative, Mirative, Epsitemic Modal [144]",
      AP_interrogative: "/",
      AP_declarative: "/",
      Diachronic: "/",
      Notes: "",
      paradigmatic: "No",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Mongsen Ao",
      Subfamily: "Ao",
      Source: "Coupe 2007",
      Coordinates: "26.32, 94.38",
      Any_Marking: "-",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "",
      AP_interrogative: "",
      AP_declarative: "",
      Diachronic: "",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Bai",
      Subfamily: "Bai",
      Source: "Wiersma 1990",
      Coordinates: "26.17, 99.71",
      Any_Marking: "-",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "",
      AP_interrogative: "",
      AP_declarative: "",
      Diachronic: "",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Mönpa",
      Subfamily: "Black Mountain",
      Source: "Hyslop 2016, Van Driem 1995",
      Coordinates: "27.21, 90.55",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "+",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "Evidential",
      AP_interrogative: "/",
      AP_declarative: "/",
      Diachronic: "/",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: "+"
    },
    {
      Language: "Atong",
      Subfamily: "Brahmaputran",
      Source: "van Breugel 2014",
      Coordinates: "25.35, 90.66",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "",
      EM1: "",
      Ev1: "+",
      Ego1: "",
      Eng1: "",
      Mir1: "+",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "Mirative [425], Quotative [408]",
      AP_interrogative: "/",
      AP_declarative: "+ [426] narrative mirative",
      Diachronic: "quotative from 'say'",
      Notes: "",
      paradigmatic: "No",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Garo",
      Subfamily: "Brahmaputran",
      Source: "Burling 2003",
      Coordinates: "25.30, 90.46",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "+",
      Ego2: "",
      Eng2: "",
      Mir2: "+",
      Term_source: "\"Terminal Suffix\", descriptions but no terms",
      AP_interrogative: "/",
      AP_declarative: "+ counterexpective? [161]",
      Diachronic: "/",
      Notes: "counterexpective uncommon, very marked?",
      paradigmatic: "No",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Hakhun Tangsa",
      Subfamily: "Brahmaputran",
      Source: "Boro 2017",
      Coordinates: "27.15, 95.39",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "",
      Ev1: "+",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "Reportative, Hearsay [352]",
      AP_interrogative: "/",
      AP_declarative: "/",
      Diachronic: "hearsay particle from 'to say'[352]",
      Notes: "",
      paradigmatic: "No",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Bhujel",
      Subfamily: "Chepangic",
      Source: "Regmi 2007",
      Coordinates: "28.01, 84.51",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "+",
      Verb_Phrase: "+",
      Discourse_particle: "",
      EM1: "+",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "",
      Ev2: "+",
      Ego2: "",
      Eng2: "",
      Mir2: "+",
      Term_source: "Mirative, Evidential",
      AP_interrogative: "/",
      AP_declarative: "/",
      Diachronic: "",
      Notes: "Evidentiality in only past tenses, mirative with nominal scope",
      paradigmatic: "No",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Chepang",
      Subfamily: "Chepangic",
      Source: "Caughley 1982",
      Coordinates: "27.72, 84.90",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "",
      Ev2: "",
      Ego2: "+",
      Eng2: "+",
      Mir2: "",
      Term_source: "Givenness, Information Flow",
      AP_interrogative: "+ [86]",
      AP_declarative: "",
      Diachronic: "",
      Notes: "",
      paradigmatic: "Full?",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Idu",
      Subfamily: "Digarish",
      Source: "Blench 2019 (unpublished)",
      Coordinates: "29.45, 95.65",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "+",
      Ev2: "+",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "Evidential",
      AP_interrogative: "?",
      AP_declarative: "?",
      Diachronic: "?",
      Notes: "Really early grammar",
      paradigmatic: "Full",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: "+"
    },
    {
      Language: "Dhimali",
      Subfamily: "Dimalish",
      Source: "King 2009",
      Coordinates: "26.63, 88.38",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "+",
      Ev2: "+",
      Ego2: "",
      Eng2: "",
      Mir2: "+",
      Term_source: "Deductive, Dubiative, Mirative",
      AP_interrogative: "/",
      AP_declarative: "/",
      Diachronic: "",
      Notes: "",
      paradigmatic: "No",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Toto",
      Subfamily: "Dimalish",
      Source: "Basumatary 2016",
      Coordinates: "26.67, 88.97",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "+",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "single Probability morpheme",
      AP_interrogative: "?",
      AP_declarative: "?",
      Diachronic: "",
      Notes: "",
      paradigmatic: "No",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Dura",
      Subfamily: "Dura",
      Source: "Schorer 2016",
      Coordinates: "28.17, 84.44",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "+",
      Other1: "+",
      EM2: "+",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "Mirative, Presumptive (EM)",
      AP_interrogative: "/",
      AP_declarative: "/",
      Diachronic: "Mirative descended from nominalisation [233]",
      Notes: "",
      paradigmatic: "No",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Kurtöp",
      Subfamily: "East Bodish",
      Source: "Hyslop 2017,2018",
      Coordinates: "27.54, 90.98",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "",
      Ev2: "+",
      Ego2: "+",
      Eng2: "+",
      Mir2: "+",
      Term_source: "Egophoricity and Mirativity, inference, dubiative and others [2018:115,134]",
      AP_interrogative: "+",
      AP_declarative: "+? [2018: 125]",
      Diachronic: "See Hyslop 2020",
      Notes: "",
      paradigmatic: "Full",
      Obligatory: "",
      Mixed_Paradigm: "+",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Tawang Monpa",
      Subfamily: "East Bodish",
      Source: "Tombleson 2020",
      Coordinates: "27.38, 91.82",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "+",
      Other1: "+",
      EM2: "",
      Ev2: "+",
      Ego2: "+",
      Eng2: "",
      Mir2: "",
      Term_source: "Perosnal,Testimonial,Neutral",
      AP_interrogative: "+",
      AP_declarative: "/",
      Diachronic: "/",
      Notes: "Copulas",
      paradigmatic: "Full",
      Obligatory: "",
      Mixed_Paradigm: "+",
      Nominal_Engagement: "",
      Thesis: "+"
    },
    {
      Language: "Ersu",
      Subfamily: "Ersuish",
      Source: "Zhang 2013",
      Coordinates: "29.29, 102.21",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "",
      Ev1: "+",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "+",
      Mir2: "",
      Term_source: "Direct, Inferred, Reportative",
      AP_interrogative: "+",
      AP_declarative: "+? [2013:547 counterexpective q tag]",
      Diachronic: "",
      Notes: "CFPs, possible engagement in question tag [547]",
      paradigmatic: "Full?",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Lizu",
      Subfamily: "Ersuish",
      Source: "Chirkova 2018",
      Coordinates: "28.33, 101.35",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "+",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "+",
      Ev2: "",
      Ego2: "+",
      Eng2: "",
      Mir2: "",
      Term_source: "First-hand, inferential, quotative; egophoric",
      AP_interrogative: "+",
      AP_declarative: "/",
      Diachronic: "Some details on reportative from \"say\", cognate in Ersu,
      Notes: "",
      paradigmatic: "Full",
      Obligatory: "Yes?",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: "+"
    },
    {
      Language: "Gongduk",
      Subfamily: "Gongduk",
      Source: "NA",
      Coordinates: "27.07, 91.17",
      Any_Marking: "NA",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "",
      AP_interrogative: "",
      AP_declarative: "",
      Diachronic: "",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Sajolang",
      Subfamily: "Hrusish",
      Source: "Weedall 2021",
      Coordinates: "27.58, 92.77",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "+",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "",
      Ev2: "+",
      Ego2: "",
      Eng2: "",
      Mir2: "+",
      Term_source: "Mirative, Evidential, Dubiative, Emphatic",
      AP_interrogative: "",
      AP_declarative: "+",
      Diachronic: "dir evidential from \"do\", assumption from \"seem\",
      Notes: "",
      paradigmatic: "No",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Kadu",
      Subfamily: "Kachinic",
      Source: "Sangdong 2012",
      Coordinates: "21.53, 100.09",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "+",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "+",
      Ego2: "",
      Eng2: "",
      Mir2: "+",
      Term_source: "Hearsay, Mirative",
      AP_interrogative: "?",
      AP_declarative: "? Mirative [404]",
      Diachronic: "",
      Notes: "Not really clear if EM is grammatical",
      paradigmatic: "No",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Turung",
      Subfamily: "Kachinic",
      Source: "Morey 2010",
      Coordinates: "27.30, 95.61",
      Any_Marking: "+?",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "+",
      Ev2: "+",
      Ego2: "",
      Eng2: "+",
      Mir2: "",
      Term_source: "Reportative Evidential [458], epistemic meanings of imperatives [455-6]",
      AP_interrogative: "/",
      AP_declarative: "/",
      Diachronic: "",
      Notes: "",
      paradigmatic: "No",
      Obligatory: "No",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Karbi",
      Subfamily: "Karbi",
      Source: "Konnerth 2020",
      Coordinates: "25.73, 93.05",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "+",
      Ev1: "+",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "Quotative, Reportative, Dubiative",
      AP_interrogative: "",
      AP_declarative: "+",
      Diachronic: "",
      Notes: "only reportative and quotative",
      paradigmatic: "Full?",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Eastern Kayah",
      Subfamily: "Karenic",
      Source: "Solnit 1986",
      Coordinates: "19.89, 98.34",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "+",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "quotative",
      AP_interrogative: "",
      AP_declarative: "/",
      Diachronic: "verb to say",
      Notes: "only one particle noted at all, honestly might be perphrastic",
      paradigmatic: "No",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Kayah Monu",
      Subfamily: "Karenic",
      Source: "Aung 2013",
      Coordinates: "19.16, 96.95",
      Any_Marking: "-",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "",
      AP_interrogative: "",
      AP_declarative: "",
      Diachronic: "",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: "+"
    },
    {
      Language: "Duhumbi",
      Subfamily: "Kho-Bwa",
      Source: "Bodt 2020",
      Coordinates: "27.42, 92.23",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "+?",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "+",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "+",
      Term_source: "Evidentiality",
      AP_interrogative: "/?",
      AP_declarative: "+ [408,413]",
      Diachronic: "Various are given in ch.8",
      Notes: "non-copula evidentials are almost secondary meanings to TAM markers?",
      paradigmatic: "No?",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Puroik",
      Subfamily: "Kho-Bwa",
      Source: "Lieberherr 2017",
      Coordinates: "27.68, 93.14",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "",
      EM1: "",
      Ev1: "+",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "Quotative",
      AP_interrogative: "",
      AP_declarative: "",
      Diachronic: "Grammaticalised from 'say'",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Chhathare Limbu",
      Subfamily: "Kiranti",
      Source: "Tumbahang 2017",
      Coordinates: "27.27, 87.89",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "",
      Ev2: "+",
      Ego2: "",
      Eng2: "",
      Mir2: "+",
      Term_source: "Descriptions given with no terms [2007]",
      AP_interrogative: "/",
      AP_declarative: "/",
      Diachronic: "As with Yakkha, borrowed from Nepali",
      Notes: "Mirative, counterexpective with spkr origo, reportative",
      paradigmatic: "No",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Yakkha",
      Subfamily: "Kiranti",
      Source: "Schackow 2015",
      Coordinates: "27.37, 87.93",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "+",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "+",
      Other1: "+",
      EM2: "+",
      Ev2: "+",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "Mirative, reportative, probability [516]",
      AP_interrogative: "",
      AP_declarative: "+",
      Diachronic: "Mirative borrowed from Nepali",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Sunwar",
      Subfamily: "Kiranti",
      Source: "Borchers 2008",
      Coordinates: "27.52, 86.25",
      Any_Marking: "-?",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "",
      AP_interrogative: "",
      AP_declarative: "",
      Diachronic: "",
      Notes: "",
      paradigmatic: "",
      Obligatory: "Yes",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Daai Chin",
      Subfamily: "Kukish",
      Source: "So-Hartmann 2008",
      Coordinates: "20.73, 93.79",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "",
      Ev1: "+",
      Ego1: "",
      Eng1: "",
      Mir1: "+",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "Mirative, Evidential",
      AP_interrogative: "?",
      AP_declarative: "/?",
      Diachronic: "",
      Notes: "Mirative always negative",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Hyow",
      Subfamily: "Kukish",
      Source: "Zakaria 2018",
      Coordinates: "21.39, 93.51",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "",
      Ev2: "+",
      Ego2: "",
      Eng2: "",
      Mir2: "+",
      Term_source: "Surprise, Unpredicted",
      AP_interrogative: "?",
      AP_declarative: "+ [437] surprising marker marks general surprise",
      Diachronic: "",
      Notes: "",
      paradigmatic: "No?",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: "+"
    },
    {
      Language: "Lepcha",
      Subfamily: "Lepcha",
      Source: "Plaisier 2007",
      Coordinates: "27.09, 88.57",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "+",
      Term_source: "Dubiative, Possibility, inferential, certainty, discovery particles",
      AP_interrogative: "/",
      AP_declarative: "+ [136,165]",
      Diachronic: "Predominantly forms of extant full verbs",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Lhokpu",
      Subfamily: "Lhokpu",
      Source: "NA",
      Coordinates: "26.91, 89.31",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "",
      EM1: "",
      Ev1: "+",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "",
      AP_interrogative: "+",
      AP_declarative: "",
      Diachronic: "",
      Notes: "",
      paradigmatic: "",
      Obligatory: "Yes",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: "+"
    },
    {
      Language: "Burmese",
      Subfamily: "Lolo-Burmese",
      Source: "Soe 1999",
      Coordinates: "20.79, 93.97",
      Any_Marking: "-?",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "",
      AP_interrogative: "",
      AP_declarative: "",
      Diachronic: "",
      Notes: "",
      paradigmatic: "",
      Obligatory: "Yes",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Nuosu (Sichuan Yi)",
      Subfamily: "Lolo-Burmese",
      Source: "Gerner 2013",
      Coordinates: "28.19, 102.12",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+ ",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "",
      Ev2: "+",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "Quotative only [377]",
      AP_interrogative: "/",
      AP_declarative: "/",
      Diachronic: "Grammaticalised from 'say' in proto-Yi",
      Notes: "",
      paradigmatic: "No",
      Obligatory: "No?",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Kham",
      Subfamily: "Magaric",
      Source: "Wattters 2002",
      Coordinates: "28.53, 82.95",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "+",
      EM1: "+",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "+",
      Other1: "+",
      EM2: "",
      Ev2: "+",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "Mirative, Counterexpective, Reportative, Possibility, Probability",
      AP_interrogative: "+ two forms of questions based on expected response",
      AP_declarative: "+ [291] mirative requires fact of discovery to be relevant to listener",
      Diachronic: "Possibly grammaticalised from 'say'",
      Notes: "[289] mirative",
      paradigmatic: "No",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Magar",
      Subfamily: "Magaric",
      Source: "Grunow-Harsta 2008",
      Coordinates: "27.41, 87.06",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "+",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "",
      Ev2: "+",
      Ego2: "",
      Eng2: "",
      Mir2: "+",
      Term_source: "Mirative, Direct/Factual. Reportative, Inferred",
      AP_interrogative: "+",
      AP_declarative: "+? [486-487, c reads a bit like IS]",
      Diachronic: "",
      Notes: "",
      paradigmatic: "No",
      Obligatory: "",
      Mixed_Paradigm: "+",
      Nominal_Engagement: "",
      Thesis: "+"
    },
    {
      Language: "Meithei",
      Subfamily: "Meithei",
      Source: "Chelliah 1997",
      Coordinates: "24.44, 93.34",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "",
      EM1: "",
      Ev1: "+",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "+",
      Mir2: "",
      Term_source: "Numerous; indirect evidence [211], attitude enclitics [250], more on [295]",
      AP_interrogative: "+ [295]",
      AP_declarative: "+",
      Diachronic: "/",
      Notes: "Many markers but no single discrete paradigm",
      paradigmatic: "No",
      Obligatory: "No",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: "+"
    },
    {
      Language: "",
      Subfamily: "Midzuish",
      Source: "NA",
      Coordinates: "",
      Any_Marking: "NA",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "",
      AP_interrogative: "",
      AP_declarative: "",
      Diachronic: "",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Hkongso",
      Subfamily: "Mru",
      Source: "Wright 2009",
      Coordinates: "21.50, 93.05",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "+",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "+",
      Term_source: "Mirative, Dubiative, Speaker Oriented Modalities",
      AP_interrogative: "/",
      AP_declarative: "/",
      Diachronic: "",
      Notes: "",
      paradigmatic: "No",
      Obligatory: "No",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Namuzi",
      Subfamily: "Naic",
      Source: "Pavlik 2017",
      Coordinates: "28.59, 101.90",
      Any_Marking: "+?",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "+",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "+",
      Term_source: "\"surprise or assurance\" [150],
      AP_interrogative: "?",
      AP_declarative: "?",
      Diachronic: "",
      Notes: "very limited",
      paradigmatic: "No",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: "+"
    },
    {
      Language: "Yongning Na",
      Subfamily: "Naic",
      Source: "Lidz 2010",
      Coordinates: "27.80, 100.90",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "",
      EM1: "",
      Ev1: "+",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "+",
      Ev2: "+",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "Common Sense, Evidentiality [476]",
      AP_interrogative: "?",
      AP_declarative: "?",
      Diachronic: "",
      Notes: "Separate common sense paradigm, nothin on evidentiality in questions",
      paradigmatic: "Full",
      Obligatory: "No",
      Mixed_Paradigm: "+",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Dolakha Newar",
      Subfamily: "Newaric",
      Source: "Genetti 2007",
      Coordinates: "27.58, 86.03",
      Any_Marking: "-",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "",
      AP_interrogative: "",
      AP_declarative: "",
      Diachronic: "",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Kathmandu Newar",
      Subfamily: "Newaric",
      Source: "Hale 1980, Hargreaves 2017",
      Coordinates: "27.67, 85.33",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "",
      Ev1: "",
      Ego1: "+",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "",
      Ev2: "+",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "Conjunct/Disjunct [Hargrave: 458], Quotative [464] and some other clause particles [465]",
      AP_interrogative: "+",
      AP_declarative: "/",
      Diachronic: "/",
      Notes: "",
      paradigmatic: "Full",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Khatso",
      Subfamily: "Ngwi-Burmese",
      Source: "Donlay 2019",
      Coordinates: "24.60, 102.40",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "+",
      Ev2: "",
      Ego2: "",
      Eng2: "+",
      Mir2: "",
      Term_source: "Strong Assertion Marker, Epistemic Emphatic Particle",
      AP_interrogative: "",
      AP_declarative: "+ [440-441]",
      Diachronic: "",
      Notes: "",
      paradigmatic: "No",
      Obligatory: "No",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: "+"
    },
    {
      Language: "Anong",
      Subfamily: "Nungish",
      Source: "Sun and Liu 2009",
      Coordinates: "27.29, 98.73",
      Any_Marking: "-",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "",
      AP_interrogative: "",
      AP_declarative: "",
      Diachronic: "",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Trung",
      Subfamily: "Nungish",
      Source: "Perlin 2020",
      Coordinates: "28.01, 98.49",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "+",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "",
      Ev2: "+",
      Ego2: "",
      Eng2: "",
      Mir2: "+",
      Term_source: "Mirative, Evidential",
      AP_interrogative: "/?",
      AP_declarative: "/?",
      Diachronic: "Some from verbs",
      Notes: "Mixed system marking TAE, Mirativity (first, secondhand miratives)",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "+",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Pyu",
      Subfamily: "Pyu",
      Source: "NA",
      Coordinates: "21.32, 95.90",
      Any_Marking: "NA",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "",
      AP_interrogative: "",
      AP_declarative: "",
      Diachronic: "",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Munya",
      Subfamily: "Qiangic",
      Source: "Bai 2019",
      Coordinates: "29.44, 101.42",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "+",
      EM1: "+",
      Ev1: "+",
      Ego1: "+",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "+",
      Ego2: "",
      Eng2: "+",
      Mir2: "+",
      Term_source: "Egophoric, Mirative, Evidential",
      AP_interrogative: "/",
      AP_declarative: "/",
      Diachronic: "Functionally very similar to Lhasa Tibetan",
      Notes: "",
      paradigmatic: "Full?",
      Obligatory: "",
      Mixed_Paradigm: "+",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Qiang",
      Subfamily: "Qiangic",
      Source: "LaPolla and Huang",
      Coordinates: "32.28, 103.19",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "+",
      Ego1: "",
      Eng1: "",
      Mir1: "+",
      Other1: "",
      EM2: "+",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "Direct, Inferential/Mirative, Hearsay",
      AP_interrogative: "+ [207]",
      AP_declarative: "/",
      Diachronic: "hearsay particle from 'to say'[204]",
      Notes: "",
      paradigmatic: "No",
      Obligatory: "",
      Mixed_Paradigm: "+",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "",
      Subfamily: "Raji-Raute",
      Source: "NA",
      Coordinates: "",
      Any_Marking: "NA",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "",
      AP_interrogative: "",
      AP_declarative: "",
      Diachronic: "",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Eastern Geshiza",
      Subfamily: "rGyalrongic",
      Source: "Honkasalo 2019",
      Coordinates: "31.10, 101.72",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "+",
      Ev1: "+",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "",
      Ev2: "+",
      Ego2: "+",
      Eng2: "+",
      Mir2: "",
      Term_source: "Evidential, Mirative, Non-Shared Information, more terms therein [582], Epistemic Certainty [575]",
      AP_interrogative: "+",
      AP_declarative: "+",
      Diachronic: "Some, various sources given for each form in chapter 9",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "+",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Khroskyabs",
      Subfamily: "rGyalrongic",
      Source: "Taylor-Adams and Lhawa 2020, Lai 2017",
      Coordinates: "31.57, 101.93",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "+",
      Ego2: "",
      Eng2: "",
      Mir2: "+",
      Term_source: "",
      AP_interrogative: "",
      AP_declarative: "",
      Diachronic: "",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "+",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Milang",
      Subfamily: "Siangic",
      Source: "Modi 2017",
      Coordinates: "28.55, 95.19",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "+",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "+",
      Ev2: "+",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "Egophoric [455], reportative, uncertain",
      AP_interrogative: "+",
      AP_declarative: "?",
      Diachronic: "Lexical verbs [460]",
      Notes: "",
      paradigmatic: "Full?",
      Obligatory: "Yes",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Southern Min",
      Subfamily: "Sinitic",
      Source: "Chen 2020",
      Coordinates: "24.99, 118.60",
      Any_Marking: "-?",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "+",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "Adverbs/Modal Verbs",
      AP_interrogative: "/",
      AP_declarative: "/",
      Diachronic: "",
      Notes: "Not really grammatical?",
      paradigmatic: "Adverbs",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Tamang",
      Subfamily: "Tamangic",
      Source: "Owen-Smith 2014",
      Coordinates: "27.32, 87.08",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "",
      Ev1: "+",
      Ego1: "",
      Eng1: "",
      Mir1: "+",
      Other1: "",
      EM2: "+",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "Mirative, Evidentiality",
      AP_interrogative: "+",
      AP_declarative: "?",
      Diachronic: "",
      Notes: "Mirative in separate system",
      paradigmatic: "Yes",
      Obligatory: "Yes",
      Mixed_Paradigm: "+",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Western Tamang",
      Subfamily: "Tamangic",
      Source: "Regmi and Regmi 2018",
      Coordinates: "28.02, 85.06",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "+",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "Mirative",
      AP_interrogative: "/",
      AP_declarative: "/",
      Diachronic: "",
      Notes: "",
      paradigmatic: "No",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Maring",
      Subfamily: "Tangkhul",
      Source: "Kanshowa 2016",
      Coordinates: "24.29, 94.07",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "+",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "+",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "+",
      Term_source: "Evidential, Mirative, Direct",
      AP_interrogative: "",
      AP_declarative: "",
      Diachronic: "",
      Notes: "Mirative and direct evidential meaning both from copula",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Galo",
      Subfamily: "Tani",
      Source: "Post 2007",
      Coordinates: "27.98, 94.69",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "+",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "Conjunct/Disjunct [607], Various Clause Final Particles [625]",
      AP_interrogative: "+ [607]",
      AP_declarative: "+? [634,639]",
      Diachronic: "Some only (Uncertainty from irrealis marker)",
      Notes: "Particles cover Mir, Ev, EM",
      paradigmatic: "Full",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Tangam",
      Subfamily: "Tani",
      Source: "Post 2017",
      Coordinates: "28.95, 94.98",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "+",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "+",
      Ev2: "+",
      Ego2: "",
      Eng2: "",
      Mir2: "+",
      Term_source: "Hearsay, Counterexpective",
      AP_interrogative: "?",
      AP_declarative: "+? [73] counterexpective",
      Diachronic: "",
      Notes: "",
      paradigmatic: "",
      Obligatory: "No",
      Mixed_Paradigm: "+",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Amdo Tibetan",
      Subfamily: "Tibetic",
      Source: "Tribur 2019",
      Coordinates: "34.52, 100.48",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "",
      EM1: "",
      Ev1: "+",
      Ego1: "+",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "",
      Ev2: "+",
      Ego2: "+",
      Eng2: "",
      Mir2: "+",
      Term_source: "Egophoricity",
      AP_interrogative: "+ [453]",
      AP_declarative: "?",
      Diachronic: "",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Hile Sherpa",
      Subfamily: "Tibetic",
      Source: "Graves 2007",
      Coordinates: "27.67, 87.00",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "",
      EM1: "",
      Ev1: "+?",
      Ego1: "+",
      Eng1: "",
      Mir1: "",
      Other1: "+",
      EM2: "",
      Ev2: "+",
      Ego2: "+",
      Eng2: "",
      Mir2: "+",
      Term_source: "Mirative, Past-Observational, Observational, Disjunct, Volitional",
      AP_interrogative: "+ [222]",
      AP_declarative: "/",
      Diachronic: "/",
      Notes: "A lot of forms not explained in terms of semantics in source - Egophoric distinction with Mirative or Evidential distinction in non-ego (ends up with Lhasa style 3 way split?). Egophoric distinction is experiential rather than volitional",
      paradigmatic: "Full",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Tshangla",
      Subfamily: "Tshangla",
      Source: "Andvik 2010, Grollman 2020, 2021",
      Coordinates: "27.37, 91.77",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "+?",
      Ev2: "+",
      Ego2: "+",
      Eng2: "",
      Mir2: "+",
      Term_source: "Subjective (Bjokapakha) [232], Mirative (Standard) [227], hearsay",
      AP_interrogative: "+  Grollman grammar [232]",
      AP_declarative: "/",
      Diachronic: "Grollman 2020b",
      Notes: "",
      paradigmatic: "Full",
      Obligatory: "Yes",
      Mixed_Paradigm: "+",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Tujia",
      Subfamily: "Tujia",
      Source: "Brassett, Brassett and Lu 2006",
      Coordinates: "28.24, 110.02",
      Any_Marking: "-",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "",
      AP_interrogative: "",
      AP_declarative: "",
      Diachronic: "",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Bunan",
      Subfamily: "West Himalayish",
      Source: "Widmer 2014, 2017",
      Coordinates: "31.30, 78.53",
      Any_Marking: "+",
      Verb_Morphology: "+",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "+",
      Ego1: "+",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "",
      AP_interrogative: "",
      AP_declarative: "+ [2014:503] conjuct portrays addressee as volitional",
      Diachronic: "Ego/non-ego in present, tibetic evidentials in past",
      Notes: "(2017) paper all about diachrony",
      paradigmatic: "Full",
      Obligatory: "No",
      Mixed_Paradigm: "+",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Chhitkul-Rakchham",
      Subfamily: "West Himalayish",
      Source: "Martinez 2021",
      Coordinates: "26.91, 89.31",
      Any_Marking: "+",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "+",
      Discourse_particle: "",
      EM1: "+",
      Ev1: "+",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "+",
      Term_source: "Perceptual, Dubiative, Assertive, Pers Experience, Pers Assertive",
      AP_interrogative: "+ [172]",
      AP_declarative: "+",
      Diachronic: "",
      Notes: "Probably in source tbh",
      paradigmatic: "Full",
      Obligatory: "",
      Mixed_Paradigm: "+",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Inpui",
      Subfamily: "Zeme",
      Source: "Devi 2014",
      Coordinates: "25.35, 93.65",
      Any_Marking: "-",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "",
      AP_interrogative: "",
      AP_declarative: "",
      Diachronic: "",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: "Zeme",
      Subfamily: "Zeme",
      Source: "Chanu 2017",
      Coordinates: "25.10, 93.79",
      Any_Marking: "-",
      Verb_Morphology: "",
      Noun_Phrase: "",
      Verb_Phrase: "",
      Discourse_particle: "",
      EM1: "",
      Ev1: "",
      Ego1: "",
      Eng1: "",
      Mir1: "",
      Other1: "",
      EM2: "",
      Ev2: "",
      Ego2: "",
      Eng2: "",
      Mir2: "",
      Term_source: "",
      AP_interrogative: "",
      AP_declarative: "",
      Diachronic: "",
      Notes: "",
      paradigmatic: "",
      Obligatory: "",
      Mixed_Paradigm: "",
      Nominal_Engagement: "",
      Thesis: ""
    },
    {
      Language: ""
    }
  ]

var table = new Tabulator("#database_table", {
    height:205, // set height of table (in CSS or here), this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
    data:tabledata, //assign data to table
    layout:"fitColumns", //fit columns to width of table (optional)
    columns:[ //Define Table Columns
        {title:"Language", field:"Language"},
        {title:"Subfamily", field:"Subfamily"},
        {title:"Coordinates", field:"Coordinates"},
        {title:"Evidence of epistemic marking", field:"Any_Marking"},
        {title:"Verb Morphology", field:"Verb_Morphology"},
        {title:"Noun Phrase", field:"Noun_Phrase"},
        {title:"Verb Phrase", field:"Verb_Phrase"},
        {title:"Discourse particle/speech act level", field:"Discourse_particle"},
        {title:"EM", field:"EM1"},
        {title:"Ev", field:"Ev1"},
        {title:"Ego", field:"Ego1"},
        {title:"Eng", field:"Eng1"},
        {title:"Mir", field:"Mir1"},
        {title:"Other", field:"Other1"},
        {title:"EM", field:"EM2"},
        {title:"Ev", field:"Ev2"},
        {title:"Ego", field:"Ego2"},
        {title:"Eng", field:"Eng2"},
        {title:"Mir", field:"Mir2"},
        {title:"Term(s) used in source", field:"Term_source"},
        {title:"Evidence of AP in interrogative structures?", field:"AP_interrogative"},
        {title:"Evidence of AP in declarative structures?", field:"AP_declarative"},
        {title:"Diachronic Source?", field:"Diachronic"},
        {title:"Obligatory", field:"Obligatory"},
        {title:"Mixed Paradigm", field:"Mixed_Paradigm"},
        {title:"Nominal Engagement", field:"Nominal_Engagement"},
        {title:"Other notes", field:"Notes"}

    ],
});